Repository themoment-team/hellogsm-server-24, pull requests merged in 2024-07, with the labels that each got.

#53 [global] 공통 response 객체 병합
  src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiMessageResponse.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiResponse.java
  src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthController.java
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
Labels: priority: high, refactor

#54 [global] 인증 로직 변경된 엔티티 적용
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/member/repo/MemberRepository.java
  src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java
Labels: feature, priority: high

#55 [member] 성별 enum class 이름 변경
  src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/request/ApplicantReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/response/FoundApplicantResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/Applicant.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/QueryApplicantByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GedAdmissionInfoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GeneralAdmissionInfoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/type/Sex.java
Labels: priority: high, refactor

#56 [member] 지원자 정보 조회 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/FoundMemberResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#57 [member] 인증코드 전송 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/ApplicantAuthenticationCode.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/repo/ApplicantCodeRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/repo/CodeRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/AuthenticateCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CommonCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/GenerateApplicantCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/QueryApplicantByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateApplicantCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateApplicantTestCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/GenerateCodeReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
  src/main/java/team/themoment/hellogsmv3/domain/member/repo/CodeRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/GenerateCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#58 [member] 인증코드 인증 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ApplicantAuthenticateCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/AuthenticateCodeReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/AuthenticateCodeService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#59 [member] Gender enum 사용처 수정
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberResDto.java
Labels: priority: high, fix

#62 [member] oauth정보 기반 member생성 method 이름 변경
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java
Labels: priority: low, refactor

#61 [member] 지원자 본인인증 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ApplicantCommonCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/CreateMemberReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#63 [member] 지원자 정보 수정 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/ModifyMemberReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/ModifyMemberService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#64 [oneseo] 원서 추가 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/annotation/ApplicationDesiredMajorsValidator.java
  src/main/java/team/themoment/hellogsmv3/domain/application/annotation/ApplicationValidDesiredMajors.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/DesiredMajorsValidator.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/ValidDesiredMajors.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/OneseoPrivacyDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/type/DesiredMajors.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/MiddleSchoolAchievementRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoPrivacyDetailRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#65 [oneseo] 원서 수정 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/OneseoPrivacyDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/ScreeningChangeHistory.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/MiddleSchoolAchievementRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoPrivacyDetailRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/ScreeningChangeHistoryRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#66 [entity] 입학시험 평가요소, 중학교 성취도 엔티티 구성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/common/converter/IntegerListConverter.java
  src/main/java/team/themoment/hellogsmv3/global/common/converter/StringListConverter.java
Labels: feature, priority: high

#70 [oneseo] 원서 최종제출 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/UpdateApplicationFinalSubmissionService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#80 [oneseo] 원서 추가, 수정시 중학교 성적 필드 네이밍 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
Labels: priority: high, refactor

#81 [oneseo] EntranceTestFactorsDetail 검정고시 관련 필드 삭제
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
Labels: priority: high, refactor

#71 [oneseo] 성적 환산 로직 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestFactorsDetailRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
Labels: feature, priority: high

#72 [oneseo] 모의성적 계산 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MockScoreResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateMockScoreService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#68 [oneseo] 원서 조회 구현
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/DesiredMajorsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/FoundOneseoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MiddleSchoolAchievementResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/OneseoPrivacyDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#69 [oneseo] 원서 검색 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/SearchApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/ApplicationSearchTag.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/TestResultTag.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/SearchOneseoPageInfoDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/SearchOneseoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/SearchOneseosResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/type/SearchTag.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#75 [thirdParty] 이미지 업로드 uri 변경
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
Labels: feature, priority: high

#78 [oneseo] 실물 원서 제출 여부 반환
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArrivedStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
Labels: feature, priority: high

#77 [oneseo] 수험표 출력 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArrivedStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsService.java
Labels: feature, priority: high

#79 [oneseo] 원서접수번호 할당 구현
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
Labels: feature, priority: high

#74 [oneseo] 적성 검사 점수 수정 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArrivedStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
Labels: feature, priority: high

#73 [oneseo] 실물 서류 제출 여부 상태 변경
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/MemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArrivedStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
Labels: feature, priority: high

#84 [member] 회원가입 서비스 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
Labels: priority: high, test

#83 [member] 인증코드 관련 서비스 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeServiceTest.java
Labels: priority: high, test

#88 [oneseo] 원서 생성 서비스 테스트코드 작성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
Labels: priority: high, test

#82 [member] 지원자 정보 조회 서비스 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdServiceTest.java
Labels: priority: high, test

#86 [ oneseo] 원서 정보 조회 서비스 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: priority: high, test

#87 [oneseo] 원서 정보 검색 서비스 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java
Labels: priority: high, test

#89 [oneseo] 심층면접점수 기입 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/InterviewScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high, fix

#92 [member] 회원 인증 정보 조회 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberAuthInfoByIdServiceTest.java
Labels: priority: low, test

#91 [member] 인증코드 전송 서비스 테스트코드 추가
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/GenerateCodeService.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImplTest.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImplTest.java
Labels: priority: high, test

#94 [member] 회원정보 수정을 막도록 변경
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/CreateMemberReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/CreateMemberReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/ModifyMemberService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: priority: high, fix

#99 [member] 테스트코드 셋업과정에서 발생하는 오류 해결
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
Labels: priority: high, fix, test

#98 [oneseo] 모의성적 계산 서비스 로직 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateMockScoreServiceTest.java
Labels: priority: high, test

#103 [oneseo] 성적 환산 서비스 로직 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeServiceTest.java
Labels: priority: high, test

#104 [global] 스프링부트 3.xx 버전에 맞도록 QueryDSL 설정 변경하여 오류 해결
  build.gradle
Labels: bug, priority: high, fix

#95 [oneseo] 심층면점 점수 기입 서비스 로직 테스트 코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java
Labels: priority: high, test

#93 [oneseo] 엑셀 출력 기능 구현
  build.gradle
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: feature, priority: high

#96 [oneseo] 수험표 출력 기능 테스트 코드 작성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsServiceTest.java
Labels: priority: low, test

#97 [thirdParty] 이미지 업로드 기능 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/thirdParty/service/UploadImageServiceTest.java
Labels: priority: low, test

#100 [oneseo] 원서 삭제 테스트코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoServiceTest.java
Labels: priority: low, test

#102 [oneseo] 적성 검사 점수 기입 테스트 코드 작성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreServiceTest.java
Labels: priority: low, test

#101 [oneseo] 실물 원서 제출 여부 변경 테스트 코드 작성
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java
Labels: priority: low, test

#107 [oneseo] 엑셀 출력 최종점수 계산식 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
Labels: priority: high, fix

#108 [oneseo] 최종제출기능 삭제 및 비즈니스 요구사항 반영
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
Labels: priority: high, fix, refactor

#109 fix(oneseo): 검정고시 환산식 소수점 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MiddleSchoolAchievementResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: priority: high, fix
