Repository themoment-team/hellogsm-server-24, pull requests merged in 2024-06, with the labels that each got.

#25 [application] 내 원서 추가
  src/main/java/team/themoment/hellogsmv3/domain/application/annotation/DesiredMajorsValidator.java
  src/main/java/team/themoment/hellogsmv3/domain/application/annotation/ValidDesiredMajors.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidateApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidateMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidatePersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GedApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GedMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GedPersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduateApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduateMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduatePersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/ApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/DesiredMajors.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationStatus.java
  src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#27 [application] 최종제출 상태 변경
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/UpdateFinalSubmissionService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#31 [applicant] 인증번호 로직에서 사용되는 AuthenticationCode 엔티티 개선
  src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/AuthenticationCode.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/repo/CodeRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/AuthenticateCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CommonCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/GenerateCodeService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateTestCodeServiceImpl.java
Labels: priority: low, refactor

#29 [application] 원서 조회 기능 구현
  build.gradle
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/AdmissionGradeResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/AdmissionInfoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/AdmissionStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/FoundApplicationResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GedAdmissionGradeResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GedAdmissionInfoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GeneralAdmissionGradeResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GeneralAdmissionInfoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidateMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidatePersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GedMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduateMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractPersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/param/AbstractPersonalInformationParameter.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/param/CandidateMiddleSchoolGradeParameter.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/ApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/custom/CustomApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/custom/CustomApplicationRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationStatus.java
  src/main/java/team/themoment/hellogsmv3/global/config/QueryDslConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#39 [application] 변경된 원서 도메인에 맞춰 원서 생성, 수정 로직 변경
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidateMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/ModifyApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationStatus.java
Labels: priority: high, fix

#37 [global] response 공통화 작업
  src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/auth/controller/AuthenticationController.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponse.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiMessageResponse.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiResponse.java
  src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
  src/main/java/team/themoment/hellogsmv3/global/exception/model/ExceptionResponseEntity.java
  src/main/resources/application.yml
Labels: priority: low, refactor

#42 [application] 원서 도메인 심층면접 점수 필드 추가 및 EvaluationResult에 누락된 필드 추가
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/AdmissionStatusResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/ApplicationDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAllApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: priority: high, fix

#32 [application] 원서 상태 변경 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationStatusReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduateApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractMiddleSchoolGrade.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractPersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/param/AbstractApplicationStatusParameter.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/ApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/UpdateApplicationStatusService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#33 [application] 수험표 출력 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduatePersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#43 [git] develop브랜치에 feature/get-admission-ticket 브랜치 적용
  src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduatePersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: low

#34 [application] 내 원서 정보 삭제 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/DeleteApplicationByAuthIdService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#35 [thirdParty] 이미지 업로드 기능 구현
  build.gradle
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/properties/S3Environment.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/service/UploadImageService.java
  src/main/resources/application.yml
Labels: feature, priority: high

#44 [application] 중복되는 컨트롤러 메서드 제거
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
Labels: priority: high, fix

#46 [applicant] 신원본인인증시 authentication의 provider_id와 provider_name이 바뀌는 오류 해결
  src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
  src/main/java/team/themoment/hellogsmv3/domain/auth/entity/Authentication.java
Labels: bug, priority: high

#47 [application] 원서 도메인 enum 타입 필드 EnumType String으로 변경
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
  src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractPersonalInformation.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
Labels: priority: high, fix

#38 [application] 원서 검색 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/SearchApplicationResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/SearchApplicationsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/ApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/custom/CustomApplicationRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/application/repo/custom/CustomApplicationRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/application/service/SearchApplicationService.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
  src/main/java/team/themoment/hellogsmv3/domain/application/type/SearchTag.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#50 [global] oauth 로그인 기능 관련 개선사항 적용
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
  src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
  src/main/java/team/themoment/hellogsmv3/domain/auth/controller/AuthenticationController.java
  src/main/java/team/themoment/hellogsmv3/global/common/handler/AuthenticationArgumentResolver.java
  src/main/java/team/themoment/hellogsmv3/global/common/handler/annotation/AuthRequest.java
  src/main/java/team/themoment/hellogsmv3/global/config/PropertiesScanConfig.java
  src/main/java/team/themoment/hellogsmv3/global/config/WebArgumentResolverConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthEnvironment.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthenticatedUserManager.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthenticatedUserManagerImpl.java
  src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java
Labels: priority: low, refactor
