Repository themoment-team/hellogsm-server-24, pull requests merged in 2024-08, with the labels that each got.

#110 [oneseo] 엑셀 출력 기능 테스트코드 작성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: priority: low, test

#113 [oneseo] 심층 면접 점수 기입 서비스로직 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java
Labels: priority: high, test

#116 [oneseo] 원서 공통 서비스로직 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
Labels: priority: high, test

#115 [member] 맴버 공통 서비스로직 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/member/service/MemberServiceTest.java
Labels: priority: high, test

#111 [oneseo] 원서 검색 N+1 문제 개선, 프로젝션 적용
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java
Labels: priority: high, refactor

#117 [oneseo] 원서 검색 총 원서 개수 조회 로직 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
Labels: bug, priority: high, refactor

#112 [global] swagger 적용
  build.gradle
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiResponse.java
  src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthController.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
  src/main/resources/application.yml
Labels: feature, priority: high

#106 [oneseo] 원서 테이블 컬럼 인덱스 생성
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
Labels: priority: high, fix

#118 [oneseo] 원서 검색 쿼리 잘못된 조건 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
Labels: bug, priority: high

#119 [global] Logging Filter 추가
  src/main/java/team/themoment/hellogsmv3/global/common/handler/AuthenticationArgumentResolver.java
  src/main/java/team/themoment/hellogsmv3/global/common/logging/LoggingFilter.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: bug, feature, priority: high

#121 [global] 특정 기간에만 사용 사능한 API 검증용 custom filter 추가
  src/main/java/team/themoment/hellogsmv3/global/config/PropertiesScanConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/data/ScheduleEnvironment.java
  src/main/java/team/themoment/hellogsmv3/global/security/filter/TimeBasedFilter.java
  src/main/resources/application.yml
Labels: feature, priority: high

#122 [member] 인증번호 전송 기능 aws sns 연동
  build.gradle
  src/main/java/team/themoment/hellogsmv3/domain/member/service/SendCodeNotificationService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/SendSmsService.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendSmsServiceImpl.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/template/AwsCallBack.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/template/AwsTemplate.java
  src/main/resources/application.yml
Labels: feature, priority: high

#120 [global] stage 환경 CD workflow 작성
  .github/workflows/hellogsm-stage-cd.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/dev-deploy.sh
  src/main/resources/application.yml
  src/test/java/team/themoment/hellogsmv3/HelloGsmV3ApplicationTests.java
Labels: priority: high, deploy

#123 [test] 인증코드 전송 테스트코드 수정
  src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImplTest.java
Labels: bug, priority: high, test

#126 [global] stage 환경 ci/cd flow 도커를 사용하도록 재구축
  .github/workflows/hellogsm-stage-cd.yml
  DockerfileStage
  scripts/deploy.sh
  scripts/dev-deploy.sh
Labels: priority: high, deploy, fix

#125 [oneseo] 원서 관련 redis 캐시 문제 개선
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/ScreeningChangeHistory.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: bug, priority: high, fix

#128 [oneseo] 원서 테스트코드 변경사항 수정
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
Labels: priority: high, fix, test

#129 [oneseo] 원서 관련 변경된 테이블 컬럼 스펙에 맞춰 엔티티 필드 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: bug, priority: high, fix

#130 [oneseo] MiddleSchoolAchievement 컨버트 메서드 null check 추가
  src/main/java/team/themoment/hellogsmv3/global/common/converter/IntegerListConverter.java
Labels: bug, priority: high, fix

#127 [cd] prod CD workflow 작성
  .github/workflows/hellogsm-prod-cd.yml
  DockerfileProd
  scripts/prod-deploy.sh
Labels: priority: high, deploy

#131 [oneseo] 수험표 출력 join 쿼리 문제 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
Labels: bug, priority: high, fix

#132 [global] 누락 된 cors 허용 메서드 PATCH 추가
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: bug, priority: high, fix

#124 [global] 로컬 테스트 환경 리다이렉트 url 변경기능 추가
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthEnvironment.java
  src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
  src/main/resources/application.yml
Labels: feature, priority: high

#133 [global] X_HG_ENV header name 변경
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
Labels: bug, priority: high, fix

#134 [oneseo] screening 관련 데이터베이스 구조 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/WantedScreeningChangeHistory.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/ScreeningChangeHistoryRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
Labels: priority: high, fix

#136 [oneseo] 원서 엑셀 출력 및 원서 관련 서비스 희망전형 적용 전형으로 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java
Labels: priority: high, fix, test

#135 [oneseo] 1차 전형 결과 산출 이후에 원서 수정 막도록 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
Labels: priority: high, fix

#137 [oneseo] 입학등록 동의서 제출 여부 수정 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/EntranceIntentionReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/SearchOneseoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyEntranceIntentionService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
Labels: feature, priority: high, fix

#138 [global] stage 환경 도커파일 jar 파일 실행시 JVM 시간 한국으로 설정
  DockerfileStage
Labels: priority: high, fix

#140 [global] 이미지 업로드 API response 스펙에 맞도록 수정
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/dto/response/UploadImageResDto.java
Labels: priority: high, fix

#141 [global] stage 환경 cloud watch 로그 수집 시스템 구축
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: feature, priority: high

#139 [oneseo] 원서 수정 가능여부 기능 구현
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/OneseoEditabilityResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoEditabilityService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoEditabilityServiceTest.java
Labels: feature, priority: high

#143 [global] prod 환경 로그 수집 모니터링 환경 구축
  src/main/resources/logback-spring.xml
Labels: feature, priority: high, fix

#144 [onseo] 원서 생성시 접수번호 할당 되도록 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
Labels: priority: high, fix
