Repository themoment-team/hellogsm-server-24, pull requests merged in 2024-10, with the labels that each got.

#177 [oneseo] tb_oneseo 테이블에 pass_yn 컬럼 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
Labels: feature, priority: high, fix

#178 [member] 중복 확인 API res dto 필드 스네이크 케이스로 변경
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundDuplicateMemberResDto.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryCheckDuplicateMemberServiceTest.java
Labels: priority: low, refactor

#179 [oneseo] 개별 학기별 예체능 환산점 계산식 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArtsPhysicalSubjectsScoreDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: feature, priority: high

#181 [oneseo] 원서 수정시 연관관계 엔티티의 참조 끊김 문제
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
Labels: priority: high, hotfix

#182 fix(member): 인증번호 유효기간 TTl 3분으로 수정
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
Labels: priority: high, hotfix

#183 [oneseo] 예체능 개별학기 환산점 3-2 학기 필드 추가 (졸업자)
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArtsPhysicalSubjectsScoreDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: priority: high, hotfix

#184 [oneseo] 예체능 개별학기 환산점, 원서 수정 관련 테스트코드 수정
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: test

#185 v20241008.0
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArtsPhysicalSubjectsScoreDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: deploy

#186 [oneseo] 특정 시점 이후에는 동작하지 않아야 하는 작업 수정 및 평가 점수 검증 메서드 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java
Labels: priority: high, hotfix

#189 v20241009.0
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java
Labels: deploy

#190 [onesoe] 테스트 중 발생한 원서 관련 트러블 슈팅
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
Labels: priority: high, hotfix

#191 [global] redis를 세션 스토리지 사용을 선언
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/resources/application.yml
Labels: priority: high, fix

#192 [oneseo] 원서 작성시 디스코드 알림 전송 기능 추가
  build.gradle
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/OneseoApplyEvent.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/DiscordAlarmClient.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Env.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/NoticeLevel.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignErrorDecoder.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/service/DiscordAlarmFeignClientService.java
  src/main/resources/application.yml
Labels: feature, priority: high

#193 [oneseo] 원서 생성 테스트코드 수정 및 불변객체 모킹 라이브러리 추가
  build.gradle
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
Labels: hotfix, test

#194 [oneseo] 현재 profile 정보 받아오는 방식 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
Labels: priority: high, fix

#195 v20241010.0
  build.gradle
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/OneseoApplyEvent.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
  src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/DiscordAlarmClient.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Env.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/NoticeLevel.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignErrorDecoder.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/service/DiscordAlarmFeignClientService.java
  src/main/resources/application.yml
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
Labels: deploy

#196 [oneseo] 평가점수 dto valid 어노테이션으로 검증하도록 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/InterviewScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
Labels: priority: high, fix

#197 v20241011.0
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/InterviewScoreReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
Labels: deploy

#198 [global] prod docker file에 system time 서울 시간대로 설정하는 커멘드 추가
  DockerfileProd
Labels: deploy, hotfix

#200 [oneseo] 변경된 디스코드 알림 API 스펙에 따라 채널 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Channel.java
Labels: priority: high, fix

#201 v20241013.0
  DockerfileProd
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Channel.java
Labels: deploy

#202 [global] HOTFIX 문자 전송 템플릿 간략화 및 수정
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java
Labels: priority: high, hotfix

#203 [global] 익명 객체 핸들링 에러 변경
  src/main/java/team/themoment/hellogsmv3/global/common/handler/AuthenticationArgumentResolver.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java
Labels: priority: high, fix

#204 원서 접수번호 할당로직 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
Labels: priority: high, fix

#205 v20241015.0
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/main/java/team/themoment/hellogsmv3/global/common/handler/AuthenticationArgumentResolver.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
Labels: deploy

#206 [oneseo] 원서 생성 트랜잭션 고립도 SERIALIZABLE로 설정하여 동시성 문제 방지
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
Labels: priority: high, fix

#207 v20241015.1
  src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
Labels: deploy

#209 v20241015.2
  src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java
Labels: deploy

#210 [oneseo] 원서 생성 로직 실행중 데드락 발생시 retry 어노테이션 추가
  build.gradle
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
Labels: priority: high, fix

#211 v20241017.0
  build.gradle
  src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
Labels: deploy

#212 [oneseo] 원서 다운로드시 접수번호 포멧 변경
  .gitignore
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: priority: high, fix

#213 [operation] 전형 결과 공개 operation 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/dto/response/AnnounceTestResultResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/entity/OperationTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/repo/OperationTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceFirstTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceSecondTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/QueryAnnounceTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberFirstTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberSecondTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryFirstTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QuerySecondTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high, fix

#214 [oneseo] 원서 조회 API 기간 필터 제외
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: priority: high, fix

#215 v20241021.0
  .gitignore
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/dto/response/AnnounceTestResultResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/entity/OperationTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/repo/OperationTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceFirstTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceSecondTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/service/QueryAnnounceTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberFirstTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberSecondTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryFirstTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QuerySecondTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
  src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: deploy

#216 [operation] operation api url 수정
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java
Labels: priority: high, hotfix

#217 v20241021.1
  src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java
Labels: deploy

#218 [oneseo] 수험표 출력 API 스펙 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsServiceTest.java
Labels: feature, priority: high

#219 v.20241021.2
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsServiceTest.java
Labels: priority: high, fix

#221 [test-result] 요구사항 변경으로 2차 전형 결과 API 반환값 수정
  src/main/java/team/themoment/hellogsmv3/domain/common/testResult/service/QueryTestResultService.java
Labels: priority: high, fix
