Repository themoment-team/hellogsm-server-24, pull requests merged in 2024-09, with the labels that each got.

#147 [test] 원서 생성시 할당되는 접수번호에 대한 테스트코드 수정
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
Labels: bug, priority: high, fix, test

#145 [member] 전형 결과 조회 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
Labels: feature, priority: high

#146 [oneseo] 모의 성적 api response 디자인에 맞게 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MockScoreResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
Labels: fix, priority: low

#148 [oneseo] 검정고시 총 점수의 범위를 벗어나는 값에 대한 예외처리
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
Labels: priority: high, fix

#149 Create Cloud Diagram
  cloud-diagram.py
Labels: docs, priority: low

#151 [oneseo] 검정고시 환산 점수가 음수가 나온다면 0점 처리하도록 예외처리 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
Labels: priority: high, fix

#150 [oneseo] 졸업연월 컬럼 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/OneseoPrivacyDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/OneseoPrivacyDetail.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: feature, priority: high

#153 [oneseo] 환산일수 계산 기능 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MiddleSchoolAchievementResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
Labels: feature, priority: high, fix

#156 [oneseo] 이미 원서 제출을 하였다면 원서 임시저장을 할 수 없도록 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
Labels: priority: high, fix

#155 [oneseo] 졸업자, 검정고시 지원자는 중학교 관련 정보를 받지 않도록 변경
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
Labels: priority: high, fix

#157 [oneseo] 원서 조회 dto 스펙에 성적 환산 값 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/FoundOneseoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateMockScoreService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: priority: high, fix

#158 [oneseo] isValidMiddleSchoolInfo 메서드 관련 테스트코드 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java
Labels: priority: high, fix, test

#159 [oneseo] 원서 조회 res dto의 환산점수 필드 네이밍 개선
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/FoundOneseoResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: priority: high, fix

#160 [oneseo] 원서 조회 dto 스펙에 개별 교과성적 환산점수 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/GeneralSubjectsScoreDetailResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
Labels: priority: high, fix

#161 [oneseo] 원서 조회시 교과성적 dto 추가되도록 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
Labels: priority: high, fix

#162 [global] date response api 구현
  src/main/java/team/themoment/hellogsmv3/domain/common/date/controller/DateController.java
  src/main/java/team/themoment/hellogsmv3/domain/common/date/dto/DateResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/common/date/service/QueryDateService.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/main/java/team/themoment/hellogsmv3/global/security/data/ScheduleEnvironment.java
  src/main/resources/application.yml
Labels: feature, priority: high

#163 [oneseo] 성적 계산시 자유학기제 학기가 공백일 시 1-1학기로 계산하도록 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
Labels: priority: high, fix

#165 [oneseo] 성적 환산시 자유학기제 학기 null, 공백 check 추가
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
Labels: priority: high, fix

#166 [oneseo] 원서 수정시에도 접수번호가 변경된 전형에 따라 수정되도록 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
Labels: priority: high, fix

#168 [oneseo] 접수번호 할당 메서드 테스트코드 추가
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
Labels: priority: high, test

#167 [oneseo] 원서 엑셀 출력시 필드 String으로 형변환
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java
Labels: priority: high, fix

#169 [global] date API swagger 설정 추가
  src/main/java/team/themoment/hellogsmv3/domain/common/date/controller/DateController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
  src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
  src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java
Labels: priority: high, fix

#170 [oneseo] 잘못된 1-1 자유학기 관련 성적계산 조건식 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
Labels: priority: high, fix

#172 [oneseo] 삭제된 도메인의 클래스를 의존하고 있는 import를 변경
  src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java
Labels: priority: high, fix, test

#173 [member] 전형 결과 조회 api 스펙에 배정 학과 추가
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberTestResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java
Labels: priority: high, fix

#174 [oneseo] 1차 합격 지원자만 수험표가 출력되도록 수정
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
Labels: priority: high, fix

#175 [oneseo] String list 컨버터 null check 추가
  src/main/java/team/themoment/hellogsmv3/global/common/converter/StringListConverter.java
Labels: priority: high, fix

#176 [member] 중복 회원가입 처리 로직 추가
  src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
  src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundDuplicateMemberResDto.java
  src/main/java/team/themoment/hellogsmv3/domain/member/repo/MemberRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryCheckDuplicateMemberService.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
  src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
  src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryCheckDuplicateMemberServiceTest.java
Labels: feature, priority: high, fix, test
